### PR TITLE
An attempt to fix auto async

### PR DESCRIPTION
**Pull request by randomtestfive**
## Problem

moves marked async run as normal moves

## Solution

run some more things at the same time

## Testing Notes

This is probably wrong, mostly Autonomous.addMoves()

### CODE REVIEW

**Comment by dracco1993** [comment]
And there are tests?!  😱   👌

**Comment by randomtestfive** [comment]
there are some tests

**Comment by randomtestfive** [comment]
I hadn't finished the async test

**Comment by dracco1993** [comment]
Erm... shoot.  I'm sorry.  Keep committing to the branch, then we can get more changes in?  :)

**Pull request merged**
